### ISSUE TITLE
How to find by ObjectId?

### ISSUE THREAD

**Issue by voronovmaksim** [ajclopez/mgs#1]
I hope this message finds you well. I wanted to reach out to express my gratitude for the wonderful tool you've developed.

**Question:**
My entity in MongoDB:
```
{
  "_id": {
    "$oid": "666fde1af688038e64d6b58a"
  },
  "warehouseId": {
    "$oid": "666f3a3ecf615a0f4d455411"
  }
}
```

Code:
````
query:= "warehouseId=666f3a3ecf615a0f4d455411"
opts := mgs.FindOption()
result, mgsErr := mgs.MongoGoSearch(query, opts)
entity, err = collection.Find(context.TODO(), result.Filter, findOpts)
````
AR: entity is not found.

How can I find the entity by the query? I understand that it is not found because "warehouseId" is an ObjectId, not a string.

As a workaround, I can do this:
````
filter := result.Filter["$and"][0].(map[string]interface{})
filter ["warehouseId"]=primitive.ObjectIDFromHex(filter ["warehouseId"])
entity, err = collection.Find(context.TODO(), result.Filter, findOpts)
````
AR: entity is found.

I see that for this purpose Casters exist, but it doesn't have an OBJECT_ID caster.

Is there any other way to find the entity by the query? 

If not, do you agree that this functionality is required? If you agree but don't have time to implement it, we can discuss the design here and I will prepare a PR. The easiest way would be to just add a new caster OBJECT_ID, but I think this is not the best solution because it will create a dependency on the MongoDB driver. I think an extension point can be created to avoid dependency on the driver.

**Comment by ajclopez** [comment]
Hi @voronovmaksim,

Thank you for reporting this issue and for your kind words about the tool.

I agree that adding functionality to handle ObjectId casting is necessary. I appreciate your detailed workaround. 

I will analyze this further to see how we can implement an extension point to handle ObjectId casting without tightly coupling it to the MongoDB driver. It’s indeed important to avoid such dependencies to keep the tool as flexible and independent as possible.

I’m planning to release a new version in a few days that should address this issue. In the meantime, if you have a solution or enhancement, please feel free to submit a PR. Your contribution would be greatly appreciated.

Thank you again for your feedback and for taking the time to help improve the tool.

**Comment by ajclopez** [comment]
Hi @voronovmaksim,

I have released version **1.1.0**, which includes support for `ObjectID`. There are a few small changes in how it is used, so please make sure to check the updated [documentation](https://github.com/ajclopez/mgs?tab=readme-ov-file#usage) for details.

I would appreciate it if you could test this new version and provide your feedback. 

Thank you very much for reporting the initial issue.

Looking forward to your comments and test results.

**Comment by voronovmaksim** [comment]
Hi @ajclopez,

Thanks a lot for implementing the feature so quickly.

I have checked it for the simple case mentioned above, and it works. Thank you. It is enough for me. 
I want to note that I haven't checked it for more complicated cases like $exists, AND, OR, and so on. My application doesn't require these right now.

I want to help make your tool better, so let me highlight my concern about your implementation:

1) What if a client like me has a document with a STRING field that looks like an OID but is actually a STRING in MongoDB? As I see it, `Primitives.ObjectID(val string)(oid interface{}, err error)` is always called, so there is no way to recognize whether the field type is STRING or OID. Therefore, I cannot decide whether to cast it to OID or not. As I understand, to cover this case, I will be forced to use a caster with `"<STRING_FIELD>": mgs.STRING` to avoid calling `Primitives.ObjectID(val string)(oid interface{}, err error)`. In my humble opinion, this is not a good practice.

If I had implemented this feature, I would have used casters. I would add a new caster like OID, and only if the caster is set, your new method would be called.

2) I would change the signature of the new method to `ObjectID(ctx context.Context, oidStr string) (interface{}, error)`. This would allow clients to pass any data to the extension point. It would require a lot of changes, so I don't think it is necessary right now. it's just a suggestion for the future.

**Comment by ajclopez** [comment]
Hi @voronovmaksim,

Thank you for testing and for your feedback. The main idea behind the implementation is to infer data types. In the case of `ObjectId`, it depends on the MongoDB drivers. The use of casters is intended for situations where you need to force the type, as you mentioned. However, if a client uses the library and tries to search by `"_id"`, which are always `ObjectID`, then they will always have to implement a caster.

Now, if someone uses a string similar to a MongoDB ObjectID, the use of casters is intended for that. Another example would be if you have a collection where you store phone numbers in E164 format, for example, `+17252800241`, as a string in your collection. However, when you use the library, it will infer it as a number. In this case, you would need to tell the library that your field for the phone number is a string through the use of caster.

I will take your suggestion into account in the future if I need to adjust the library. Please feel free to report any other issues you encounter.

Thank you again for your contributions and for helping me improve the library.

**Comment by voronovmaksim** [comment]
@ajclopez Hi.
FYI: The same issue i faced for `primitive.Decimal128`. Can i prepare PR with the same fix?

**Comment by ajclopez** [comment]
Hi @voronovmaksim,

Apologies for the delayed response! Could you please open a new issue for this since this one is already closed? And of course, feel free to submit a PR with the fix!
