### ISSUE TITLE
Advanced searching using POST api

### ISSUE THREAD

**Issue by mukul-agarwal-wbd** [ajclopez/mgs#2]
Hey @ajclopez 
I was going through the library and it seems very useful. However, there was one thing that I wanted to discuss which is the length of the query param in case of advanced search. Suppose there is multiple level of nested query like (((A OR B) AND (C AND D)) OR E.... where A,B,C,D,E could be filed names or queries in themselves. Thus scalability could be an issue in case of big queries. Could this be done in a POST call where there is a JSON payload (dont know how it would look like) which gets converted to BSON at the server level?

**Comment by ajclopez** [comment]
Hi @mukul-agarwal-wbd,

Thank you for your feedback and for bringing this up. I apologize for the delayed response.

Regarding the concern about the length of the query parameter in advanced searches, you are right that scalability can become an issue with large queries. Currently, a solution in your API could be to receive the advanced query via a POST request and use the library, taking into account that the string length in Go depends on the machine's architecture and the operating system's memory.

Another alternative is to define a JSON-like query language similar to GraphQL. This approach would require some development work, but it could provide a more scalable and flexible solution for handling complex queries. Any contributions or suggestions on this are welcome and would be greatly appreciated.
